force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Of Attendees</description>
    <inlineHelpText>Enter Attendee of Email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organizer of Event</description>
    <inlineHelpText>Enter your Organizer Name</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Location_of_event__c.field-meta.xml
<CustomField>
    <fullName>Location_of_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of Event</description>
    <inlineHelpText>Enter Location of Event</inlineHelpText>
    <label>Location of event</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>Name Of Event</description>
    <inlineHelpText>Please enter your Event Name</inlineHelpText>
    <label>Name of Event</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Starting Time Of Event</description>
    <inlineHelpText>Enter Your Starting Time</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>User Email Address</description>
    <inlineHelpText>Enter Your Email Address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeHandler.cls
public  class EventAttendeeHandler {
    public static void sendConfirmationEmail (List<Event_Attendee__c> newRecordList){
        Set<Id> attendeesIdsSet = new Set<Id>();
        Set<Id> eventIdsSet = new Set<Id>();
        for(Event_Attendee__c EventAttendee : newRecordList){
            attendeesIdsSet.add(EventAttendee.Attendee__c);
            eventIdsSet.add(EventAttendee.Event__c);
        }
        Map<Id,Attendee__c> attendeeMap = new Map<Id,Attendee__c>( [Select Id, Name, Email__c From Attendee__c WHERE Id IN : attendeesIdsSet]);
        Map<Id, Event_Details__c > eventMap = new Map<Id, Event_Details__c > ( [Select Id, Name,Name_of_Event__c, Start_Date_Time__c,Event_Organizer__c , Event_Organizer__r.Name, Location_of_event__r.Name FROM Event_Details__c WHERE ID IN: eventIdsSet]);
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(Event_Attendee__c eventAttendee:newRecordList){
            Attendee__c Attendee = attendeeMap.get(EventAttendee.Attendee__c);
            Event_Details__c evt = eventMap.get(EventAttendee.Event__c);  
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Pass for the '+evt.Name_of_Event__c);
            List<String> toAddress = new List<String>();
            toAddress.add(Attendee.Email__c);
            mail.setToAddresses( toAddress );
            mail.setSenderDisplayName(evt.Event_Organizer__r.Name);
            String emailBody = 'Dear '+ Attendee.Name + ',<br/><br/>'+ 'Thank you for registering for'+evt.Name+' which will be Organized on '+evt.Start_Date_Time__c+' & will be held in '+evt.Location_of_event__r.Name+'.<br/>Weare excited to have you,'+ 'see you in the event. <br/>'+'Thanks,<br/>'+evt.Event_Organizer__r.Name;
            mail.setHtmlBody(emailBody);
            emailList.add(mail);
        }
        List<Messaging.SendEmailResult> results=Messaging.sendEmail(emailList,false);
        for(Messaging.SendEmailResult email:results){
            System.debug(email.isSuccess());
        }
    }
}