force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Address_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Address_of_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address of Event</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeForm.cls
public class EventAttendeeForm {

    public Attendee__c attendee{get; set;}
    public Event_Attendee__c eventAttendee{get; set;}
    public Location_Address_Book__c location{get; set;}
    public EventAttendeeForm() {
        attendee=new Attendee__c();
        eventAttendee=new Event_Attendee__c();
        location=new Location_Address_Book__c();
        Id eventId=Apexpages.currentPage().getParameters().get('id');
        if(eventId != null){
            eventAttendee.Event__c=eventId;
        }
    }
    public void addEventAttendee(){
        try{
            insert location;
            attendee.Address_of_Event__c=location.Id;
            insert attendee;
            eventAttendee.Attendee__c=attendee.Id;
            insert eventAttendee;
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }
}