force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Location_of_event__c.field-meta.xml
<CustomField>
    <fullName>Location_of_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of Event</description>
    <inlineHelpText>Enter Location of Event</inlineHelpText>
    <label>Location of event</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>Name Of Event</description>
    <inlineHelpText>Please enter your Event Name</inlineHelpText>
    <label>Name of Event</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Starting Time Of Event</description>
    <inlineHelpText>Enter Your Starting Time</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventEmailAttendeeHandler.cls
public class EventEmailAttendeeHandler {
    public static void sendConfirmationMail(List<Event_Attendee__c> newRecordList) {
        List<Messaging.Email> emailList=new List<Messaging.Email>();
        for(Event_Attendee__c eventAttendees:newRecordList){
            Messaging.SingleEmailMessage mails=New Messaging.SingleEmailMessage();
            mails.setToAddresses(new string[] {eventAttendees.Attendee__r.Email__c});
            mails.setSubject('Pass for the'+ eventAttendees.Event__r.Name_of_Event__c);
            String body='Dear '+eventAttendees.Attendee__r.Name+ ',<br/><br/>'+'Thank you for registering for   '+' '+
            eventAttendees.Event__r.Name_of_Event__c +' which will be Organized on '+eventAttendees.Event__r.Start_Date_Time__c +
            ' & will be held in '+ eventAttendees.Event__r.Location_of_event__r.Country__c +'.<br/>We'+' '+'are excited to have you,'+'see you in the event. <br/>'+
            'Thanks';
            
            mails.setHtmlBody(body);   
            emailList.add(mails);   
        }
        Messaging.sendEmail(emailList);     
    }
}