force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Ending date and Time of Event</description>
    <inlineHelpText>Enter the End Time of your Event</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Event Type</description>
    <inlineHelpText>Event Type</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Live event or Not?</description>
    <inlineHelpText>Live event or Not?</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>Name Of Event</description>
    <inlineHelpText>Please enter your Event Name</inlineHelpText>
    <label>Name of Event</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Starting Time Of Event</description>
    <inlineHelpText>Enter Your Starting Time</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event_Details__c.field-meta.xml
<CustomField>
    <fullName>Event_Details__c</fullName>
    <label>Event Details</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckDuplicateSpeakerBookingTest.cls
@isTest
private class CheckDuplicateSpeakerBookingTest {
    @isTest
    static void TesteventSpeakerDuplicateTest() {
        Event_Details__c firstEvent = new Event_Details__c();
        firstEvent.Name_of_Event__c = 'Shirley1 Concert1';
        firstEvent.Live__c = true;
        firstEvent.Recurring__c=true;
        firstEvent.Frequency__c='Weekly';
        firstEvent.Start_Date_Time__c = Datetime.now().addDays(3);
        firstEvent.End_Date_Time__c = Datetime.now().addDays(5);
        firstEvent.Event_Type__c = 'Virtual';
        insert firstEvent;

        Event_Details__c secondEvent = new Event_Details__c();
        secondEvent.Name_of_Event__c = 'Disco1 Night1';
        secondEvent.Live__c = true;
        secondEvent.Recurring__c=true;
        secondEvent.Frequency__c='Daily';
        secondEvent.Start_Date_Time__c = Datetime.now().addDays(5);
        secondEvent.End_Date_Time__c = Datetime.now().addDays(7);
        secondEvent.Event_Type__c = 'Virtual';
        insert secondEvent;

        Speaker__c newSpeaker = new Speaker__c();
        newSpeaker.Name = 'Shirley12';
        insert newSpeaker;

        Event_Speaker__c oldEvent = new Event_Speaker__c();
        oldEvent.Event_Details__c = firstEvent.Id;
        oldEvent.Speaker__c = newSpeaker.Id;
        insert oldEvent;

        Event_Speaker__c newEvent = new Event_Speaker__c();
        newEvent.Event_Details__c = secondEvent.Id;
        newEvent.Speaker__c = newSpeaker.Id;
        Test.startTest();
        try {
            insert newEvent;
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Duplicate booking found'), 'Unexpected error message: ' + e.getMessage());
        }
        Test.stopTest();
     }
}