force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organizer of Event</description>
    <inlineHelpText>Enter your Organizer Name</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Event Type</description>
    <inlineHelpText>Event Type</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Location_of_event__c.field-meta.xml
<CustomField>
    <fullName>Location_of_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location of Event</description>
    <inlineHelpText>Enter Location of Event</inlineHelpText>
    <label>Location of event</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User Address</description>
    <inlineHelpText>Enter Your Address</inlineHelpText>
    <label>Location(Address Book)</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Event Organizers</relationshipLabel>
    <relationshipName>Event_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventOrganizerFrom.cls
public class EventOrganizerFrom {
    
    public Event_Organizer__c eorganizer{get; set;}
    public Event_Details__c event{get; set;}
    public Location_Address_Book__c location{get; set;}

    public EventOrganizerFrom(){
        eorganizer= new Event_Organizer__c();
        event= new Event_Details__c(); 
        location= new Location_Address_Book__c();
        
    }
    public void addEventOrganizer(){
        try{
            insert location;
            eorganizer.Location_Address_Book__c=location.Id;
            insert eorganizer;  
            event.Event_Organizer__c=eorganizer.Id;
            if(event.Event_Type__c!='Virtual'){
                event.Location_of_Event__c=location.Id;}
            insert event;
            
        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }
}