force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event_Details__c.field-meta.xml
<CustomField>
    <fullName>Event_Details__c</fullName>
    <label>Event Details</label>
    <referenceTo>Event_Details__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventSpeakerForm.cls
public class EventSpeakerForm {
    public Speaker__c speaker{get; set;}
    public Event_Speaker__c eventSpeaker{get; set;}

    public EventSpeakerForm() {
        speaker= new Speaker__c();
        eventSpeaker=new Event_Speaker__c();
        Id eventId=Apexpages.currentPage().getParameters().get('id');
        if(eventId != null){
            eventSpeaker.Event_Details__c=eventId;
        }
    }
    public void addSpeaker(){
        try{
            insert speaker;
            eventSpeaker.Speaker__c=speaker.Id;
            insert eventSpeaker;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM,'Record Inserted'));
        }
        catch(Exception e){
            System.debug(e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL,'Record Not Inserted'));
        }
    }
}