force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>Ending date and Time of Event</description>
    <inlineHelpText>Enter the End Time of your Event</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Live event or Not?</description>
    <inlineHelpText>Live event or Not?</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PurgeOldEventsBatch.cls
public class PurgeOldEventsBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query='Select Id From Event_Details__c where End_Date_Time__c < LAST_N_MONTHS:2 AND Live__c = True';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Event_Details__c> scope){
        delete scope;
    }
    public void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[]{'devang.tiwari@Mirketa.com'});
        mail.setSubject('Batch job complete');
        mail.setPlainTextBody('Execution of the batch has been processed.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}