force-app/main/default/objects/Event_Details__c/Event_Details__c.object-meta.xml
<CustomObject>
    <label>Event Details</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Details__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Organizer of Event</description>
    <inlineHelpText>Enter your Organizer Name</inlineHelpText>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Event Details</relationshipLabel>
    <relationshipName>Event_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Maximum Seats Required</description>
    <inlineHelpText>Enter your Maximum Seats Required</inlineHelpText>
    <label>Max Seats</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Name_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Event__c</fullName>
    <description>Name Of Event</description>
    <inlineHelpText>Please enter your Event Name</inlineHelpText>
    <label>Name of Event</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Details__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <description>Starting Time Of Event</description>
    <inlineHelpText>Enter Your Starting Time</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>User Email Address</description>
    <inlineHelpText>Enter Your Email Address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventWebServicesTest.cls
@isTest
private class EventWebServicesTest {
    
    @isTest static void testGetEventById() {
        Id recordId=createTestRecord();
        RestRequest request = new RestRequest();
        request.requestUri ='https://yourInstance.my.salesforce.com/services/apexrest/Event_Details__c/'+ recordId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        Event_Details__c thisEvent = EventWebServices.EventServices();
        System.assert(thisEvent != null);
        System.assertEquals('Test record', thisEvent.Name_of_Event__c);
    }
    static Id createTestRecord() {
        // Create test record
        Event_Details__c EventTest = new Event_Details__c(
            Name_of_Event__c='Test record', 
            Start_Date_Time__c=Date.newInstance(2021, 10, 21),
            Max_Seats__c=100);
            //Event_Organizer__r.Name ='Anurag',
            //Event_Organizer__r.Email__c='xyz@gmail.com');
        insert EventTest;
        return EventTest.Id;
    }          
}